# Fish shell completion for LOGOS - Unified AI Agent Federation
# Install: copy to ~/.config/fish/completions/logos.fish

# Global options
complete -c logos -l help -d "Show help message"
complete -c logos -l version -d "Show version"
complete -c logos -l mode -d "Select mode" -xa "daedelus deus"
complete -c logos -l list-agents -d "List all agents for current mode"
complete -c logos -l list-aliases -d "List all available aliases"

# Daedelus agent keys
complete -c logos -a "A1" -d "The Architect - System design"
complete -c logos -a "A2" -d "The Logic Engineer - Core logic"
complete -c logos -a "A3" -d "The Interface Designer - UI/UX"
complete -c logos -a "A4" -d "The Test Engineer - Test creation"
complete -c logos -a "A5" -d "The Scribe - Documentation"
complete -c logos -a "B6" -d "The Sentinel - Security review"
complete -c logos -a "B7" -d "The Marshal - Code style"
complete -c logos -a "B8" -d "The Profiler - Performance"
complete -c logos -a "B9" -d "The Critic - Code quality"
complete -c logos -a "B10" -d "The Gatekeeper - Release validation"
complete -c logos -a "C1" -d "The Bug Hunter - Bug fixing"
complete -c logos -a "C6" -d "The Security Patcher - Security patches"
complete -c logos -a "C7" -d "The Doc Updater / Manual Keeper"
complete -c logos -a "C8" -d "The Configurator / Sysctl Tuner"
complete -c logos -a "C9" -d "The Optimizer - Optimization"
complete -c logos -a "C10" -d "The Janitor - Cleanup"
complete -c logos -a "C11" -d "The Librarian / Port Librarian"
complete -c logos -a "D2" -d "The Feature Sprinter / Port Builder"
complete -c logos -a "D3" -d "The Refactorer / Compatibility Engineer"
complete -c logos -a "D4" -d "The UI Tweaker / Jail Architect"
complete -c logos -a "D5" -d "The Test Extender / ZFS Engineer"
complete -c logos -a "E1" -d "The Orchestrator - System orchestration"
complete -c logos -a "E2" -d "The OCM / Administrator"
complete -c logos -a "E3" -d "Daedelus / General Manager"
complete -c logos -a "E4" -d "The Ombudsman (DEUS only)"
complete -c logos -a "E5" -d "DEUS (DEUS only)"

# Built-in aliases
complete -c logos -a "architect" -d "Alias for A1"
complete -c logos -a "logic" -d "Alias for A2"
complete -c logos -a "interface" -d "Alias for A3"
complete -c logos -a "scribe" -d "Alias for A5"
complete -c logos -a "sentinel" -d "Alias for B6"
complete -c logos -a "security" -d "Alias for B6"
complete -c logos -a "marshal" -d "Alias for B7"
complete -c logos -a "profiler" -d "Alias for B8"
complete -c logos -a "critic" -d "Alias for B9"
complete -c logos -a "gatekeeper" -d "Alias for B10"
complete -c logos -a "bughunter" -d "Alias for C1"
complete -c logos -a "orchestrator" -d "Alias for E1"
complete -c logos -a "kernel" -d "Alias for A1 (DEUS)"
complete -c logos -a "driver" -d "Alias for A2 (DEUS)"
complete -c logos -a "network" -d "Alias for A3 (DEUS)"
complete -c logos -a "jail" -d "Alias for D4 (DEUS)"
complete -c logos -a "zfs" -d "Alias for D5 (DEUS)"
complete -c logos -a "admin" -d "Alias for E2 (DEUS)"
complete -c logos -a "deus" -d "Alias for E5 (DEUS)"
